#!/usr/bin/env python3
import hashlib
import json
import os
import os.path
import shellish


@shellish.autocommand
def addblocklisted(zwift_id, dryrun=False):
    project_root = os.path.join(os.path.dirname(os.path.realpath(__file__)), '..')
    fname = os.path.join(project_root, 'products/sauce4zwift/exclusions.json')
    with open(fname) as f:
        blocklist = json.load(f)
    idhash = hashlib.sha256(zwift_id.encode()).hexdigest()
    blocklist.append({"idhash": idhash})
    if not dryrun:
        with open(fname, 'w') as f:
            json.dump(blocklist, f, indent=4)
        os.system(f'cd {project_root}; git commit products/sauce4zwift/exclusions.json && git push')
    else:
        print('Zwift ID:', idhash)

addblocklisted()
