#!/usr/bin/env python3

import hashlib
import json
import os.path
import shellish


@shellish.autocommand
def addpatron(strava_id, patreon_id, level=10):
    project_root = os.path.join(os.path.dirname(os.path.realpath(__file__)), '..')
    fname = os.path.join(project_root, 'patrons.json')
    with open(fname) as f:
        patrons = json.load(f)
    sidhash = hashlib.sha256(strava_id.encode()).hexdigest()
    pidhash = hashlib.sha256(patreon_id.encode()).hexdigest()
    patrons[sidhash] = {
        "level": level,
        "pidhash": pidhash
    }
    with open(fname, 'w') as f:
        json.dump(patrons, f, indent=4)
    os.system(f'cd {project_root}; git commit patrons.json && git push')

addpatron()



